---

- name: Install python3 and pip
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - python3
    - python3-pip
  become: yes

- name: Ensure installation directory exists
  file:
    path: /opt/back
    state: directory
  become: yes

- name: Install application
  unarchive:
    src: ./back.tar.bz2
    dest: /opt/back
  become: yes
  notify:
    - Restart back service

- name: Install python dependencies
  pip:
    requirements: /opt/back/requirements.txt
  become: yes

- name: Install service
  copy:
    src: back.service
    dest: /etc/systemd/system/back.service
  become: yes
  notify:
    - Reload back service
    - Restart back service

- name: Ensure service is started
  service:
    name: back
    state: started
  become: yes

- name: Ensure service is enabled
  service:
    name: back
    enabled: yes
  become: yes
